export enum PaymentType {
  STAY_PAYMENT = 'STAY_PAYMENT',
  RESERVATION_DEPOSIT = 'RESERVATION_DEPOSIT',
  POS_SALE = 'POS_SALE',
  ROOM_CHARGE = 'ROOM_CHARGE',
  ROOM_CHARGE_SETTLE = 'ROOM_CHARGE_SETTLE',
}
