export enum ProductCategory {
  BEVERAGE_WATER = 'BEVERAGE_WATER',
  BEVERAGE_ENERGY = 'BEVERAGE_ENERGY',
  BEVERAGE_ALCOHOL = 'BEVERAGE_ALCOHOL',
  SNACK_CANDY = 'SNACK_CANDY',
  SNACK_SAVORY = 'SNACK_SAVORY',
}
